# Generated by Django 6.0.3 on 2026-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food & Drinks'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('health', 'Health & Medical'), ('utilities', 'Utilities & Bills'), ('education', 'Education'), ('travel', 'Travel'), ('groceries', 'Groceries'), ('rent', 'Rent & Housing'), ('subscription', 'Subscriptions'), ('other', 'Other')], default='other', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('expense_time', models.DateTimeField()),
                ('logged_time', models.DateTimeField(auto_now_add=True)),
                ('raw_input', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_time'],
            },
        ),
    ]
