# Generated by Django 6.0.3 on 2026-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
